seed: 336018

# Experiment configs
user: 'Noga'
experiment_name: 'Classifier_train'

# ClearML configs
clearml: True

# Trainer configs
train_prec: 80
batch_size: 8
lr: 0.0001
loss: 'binary_cross_entropy'
optimizer: 'AdamW'
lr_scheduler: 'ReduceLROnPlateau'
epochs: 30
early_stopping_patience: 10
output_model_path: 'model.pth'

# Dataset configs
sample_length: 10 
overlap: False