seed: 336018

# Experiment configs
user: 'tcml'
experiment_name: 'DCGAN_noise_size_1000_lr_1e-5'
debug: False
debug_ratio: 0.01
debug_epochs: 3
bsqi_th: 0.925

# ClearML configs
clearml: False

# Trainer configs
train_prec: 80
batch_size: 32
lr: 0.00001
loss: 'binary_cross_entropy'
optimizer: 'AdamW'
lr_scheduler: 'ReduceLROnPlateau'
epochs: 100
early_stopping: False
early_stopping_patience: 10
output_model_path: 'model.pth'
classifier_th: 0.75

# Dataset configs
sample_length: 30
fs: 250
overlap: 0

# GAN configs
GAN_epochs: 1000
GAN_batch_size: 64
GAN_label: 1
noise_size : 1000