channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.16
  - pip=23.0.1
  - pip:
    - airspeed==0.5.20
    - certifi==2022.12.7
    - cffi==1.15.1
    - charset-normalizer==3.1.0
    - contourpy==1.0.7
    - cycler==0.11.0
    - fonttools==4.39.3
    - fvcore==0.1.5.post20221221
    - idna==3.4
    - importlib-resources==5.12.0
    - jinja2==3.1.2
    - kiwisolver==1.4.4
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - mne==1.3.1
    - ninja==1.11.1
    - numpy==1.24.3
    - pandas==2.0.0
    - pecg==2.0.2
    - pillow==9.5.0
    - pooch==1.7.0
    - py-ecg-detectors==1.3.4
    - pycparser==2.21
    - pyparsing==3.0.9
    - pytorch-ranger==0.1.1
    - pytz==2023.3
    - requests==2.29.0
    - rtpt==0.0.4
    - scipy==1.10.1
    - setproctitle==1.3.2
    - soundfile==0.12.1
    - torch==1.8.1+cu111
    - torch-optimizer==0.1.0
    - torchaudio==0.8.1
    - tqdm==4.65.0
    - tzdata==2023.3
    - urllib3==1.26.15
    - wfdb==4.1.1

