seed: 336018

# Experiment configs
user: 'tcml'
experiment_name: 'Classifier_real_data_20sec'
debug: False
debug_ratio: 0.01
debug_epochs: 3
bsqi_th: 0.925
real_data_path: '/tcmldrive/NogaK/ECG_classification/fixed_datasets/dataset_len20_overlab0_chan0'
real_data_df_path: '/tcmldrive/NogaK/ECG_classification/experiments/tcml_classifier_real_data_training_balanced_classes_20230630_18_28_45/dataframes/'
fake_data_path: '/tcmldrive/NogaK/ECG_classification/data/fake_data_6_secs_50000_samples_gen2/'

# # Baseline 80% Normal class
# ckpt_for_inference: '/tcmldrive/NogaK/ECG_classification/experiments/tcml_classifier_train_on_dataset_with_80%_normal_intervals_20230712_20_07_46/models/epoch_13_model.pth'
# Baseline clsfr (60% Normal class)
ckpt_for_inference: '/tcmldrive/NogaK/ECG_classification/experiments/tcml_classifier_real_data_training_balanced_classes_20230630_18_28_45/models/epoch_16_model.pth'
# # Gen1 clsfr
# ckpt_for_inference: '/tcmldrive/NogaK/ECG_classification/experiments/Classifier_mixed_data_5000_fake_samples_20230630_23_28_22/models/epoch_17_model.pth'
# # Gen2 clsfr
# ckpt_for_inference: '/tcmldrive/NogaK/ECG_classification/experiments/Classifier_mixed_data_10k_fake_samples_gen2_20230701_11_04_06/models/epoch_15_model.pth'

# ClearML configs
clearml: True

# Trainer configs
train_prec: 80
batch_size: 512
lr: 0.0001
loss: 'binary_cross_entropy'
optimizer: 'AdamW'
lr_scheduler: 'ReduceLROnPlateau'
epochs: 50
early_stopping: True
early_stopping_patience: 10
output_model_path: 'model.pth'
classifier_th: 0.75

# Dataset configs
sample_length: 6
fs: 250
overlap: 0
# fake_prec: 20

# GAN configs
GAN_epochs: 500
GAN_batch_size: 256
GAN_label: 0
noise_size : 100
discriminator_lr : 0.00001
generator_lr : 0.0001
