seed: 336018

# Experiment configs
user: 'tcml'
experiment_name: 'external_dataset_evaluation'
debug: False
debug_ratio: 0.01
debug_epochs: 3
bsqi_th: 0.925

# ClearML configs
clearml: False

# Trainer configs
train_prec: 80
batch_size: 512
lr: 0.0001
loss: 'binary_cross_entropy'
optimizer: 'AdamW'
lr_scheduler: 'ReduceLROnPlateau'
epochs: 50
early_stopping: True
early_stopping_patience: 10
output_model_path: 'model.pth'
classifier_th: 0.75

# Dataset configs
sample_length: 6
fs: 250
overlap: 0
fake_prec: 100

# GAN configs
GAN_epochs: 500
GAN_batch_size: 256
GAN_label: 0
noise_size : 100
discriminator_lr : 0.00001
generator_lr : 0.0001
